# Generated by Django 5.1.1 on 2024-10-12 00:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
